### ISSUE TITLE
recaptcha missing for slackin widget

### ISSUE THREAD

**Issue by lucymhdavies** [QueerCodeOrg/queercodeberlin.github.io#27]
Something I didn't notice when I added the widget to the site...

It has reCAPTCHA working on the https://slackinvite-qcldn.herokuapp.com/ directly, but the widget version on queer-code.org isn't working.

Hopefully a missed config when I added it, and thus an easy fix. But might be a bug with slackin itself, so worth checking known issues:
https://github.com/rauchg/slackin/issues

in the queer-code.org widget:

```
<div class="g-recaptcha" data-sitekey="undefined"></div>
```

on https://slackinvite-qcldn.herokuapp.com/

```
<div class="g-recaptcha" data-sitekey="6Lf-MikUAAAAAFPg9M5Q_au-hIdfVST8oLW9Cnmx">
```

So need to get that working. Could be someting missing, or could be a slackin issue

**Comment by chromy** [comment]
Pretty sure it's a slackin bug, seems like this line in the iframe code path:
https://github.com/rauchg/slackin/blob/master/lib/index.js#L248
should pass `gcaptcha_sitekey` like this line does https://github.com/rauchg/slackin/blob/master/lib/index.js#L97

**Comment by chromy** [comment]
I put together a fix which seems to work when I test it locally: https://github.com/chromy/slackin/commit/c12cc051fb2a3d77397148f565377daa75abec6a
I'll send it as a pull request tomorrow.

**Comment by lucymhdavies** [comment]
Well spotted!

**Comment by chromy** [comment]
Okay sent https://github.com/rauchg/slackin/pull/353 :smiley: The last merged pull request was Aug 2nd though so it might be a while before it gets merged...

**Comment by franziskas** [comment]
@chromy I've deployed your master on heroku but I'm not sure it's working.

**Comment by chromy** [comment]
Hmm, yeah I think I was looking at the wrong page when I was testing. @franziskas could you try again with https://github.com/chromy/slackin, I updated my commit and hopefully got it right this time. 🤞

**Comment by franziskas** [comment]
@chromy - the capture is there but unfortunately no button to register - reverting for now
<img width="391" alt="screen shot 2017-11-24 at 07 22 15" src="https://user-images.githubusercontent.com/5154737/33199420-3ab1227c-d0e8-11e7-9f79-01a56bbd5ca3.png">

**Comment by lucymhdavies** [comment]
Ah. That'll be a CSS issue, I imagine. The Register button is probably hidden beneath the bottom of the widget.

**Comment by dirv** [comment]
I’ve updated our Heroku instance to the latest Slackin. Got a warning about an outdated Stack on Heroku, I’ll raise another issue for that.
