### ISSUE TITLE
A Mission/Vision statement for QC

### ISSUE THREAD

**Issue by kimadactyl** [QueerCodeOrg/queercodeberlin.github.io#29]
Heya, I'm speaking at an event in Jan and noticed this. I added a note to the Google Doc about it and got invited to make a change but don't really feel comfortable doing a PR for a group I've not even been to yet :). Usually you do mission statements along with a Vision Statement - so you kind of have a "what we do" and "what the end goal is" kind thing.

I'd say a mission statement for QC would have some or all of the following:

- To create safe(r) spaces for (the identities you have already listed) to (socialise? network? learn?)
- To make (programming? computing?) a better place for (the identities listed) by (having meetings?)
- Establishing a (European? International?) network of (the identities) who are working on (the issues)
- Challenging and changing structural inequalities around sexuality and gender in (computing? programming?)
- Aiding and enabling people disadvantaged due to gender and/or sexuality to get into (computing) 

A vision could be something like:

- Making (programming? computing?) industries and practice a safe and equal space for (the identities)
- Creating a world free of discrimination from gender and sexual discrimination, starting with (computing)
- Making diversity and pay in (programming) reflect that in the rest of the world / across the sector

Hope that gets the juices flowing - mission statements should be a real rallying statement for me, codes of conducts are necessary but a tactic not a strategy, something that we should aim to not need but sadly do.

I'd also consider adding an intersectional statement about how people of diverse gender and sexuality are also of many races, abilities, religions, etc... and that there is no hierarchy of oppression.

BTW I strongly dislike the sentiment behind statements like "We want to be with people like us" and/or "a place for like-minded people" - I personally think they are anti-diversity statements that suggest there is a shared commonality between queer people and we are all the same on some level. I think this is colonialist thought that stands in the way of true diversity but I understand the thought behind it :)

In terms of "the identities" I prefer "people of all genders and sexualities" as this doesn't require self-identification (something fraught in itself) personally.

What do you lot think?

Kim

**Comment by chromy** [comment]
This raises many good points. It would be great to have a discussion on these topics and to get the views of others in the QC community.

@kimadactyl There is a lot to consider here. If it is okay with you to better facilitate the discussion I will split this issue into two smaller ones:
- What ought the mission/vision statement for QC be?
- How to address any issues with the current /mission page.

(PS: @kimadactyl Feel free to join the Slack if you like, https://slackinvite-qcldn.herokuapp.com/ :).

**Comment by kimadactyl** [comment]
Yeah sounds like a great split as what needs to go where is a later decision probably. 

Point 1 then could be a bit more super zoomed out like this:

**Ontology:** Why exist in the first place? (Zoomed out vision statement - connect to queer theory, post colonialism, etc?)
**Epistemology:** How does QC think it can make a difference? (Mission statement - as above)
**Methodology:** How will it go about making that difference? (Meetings, slack, other comms, i.e. the stuff you are currently doing)
**Methods:** What will individual meetings etc be like? (Code of conduct, layout of events, etc, tactical considerations of each intervention)

(Apols for academic vocab but I find it v useful to tease stuff apart!)

Thanks for Slack invite - I find I have too much already occupying my extremely fickle attention and Slack is a distraction I don't need but may pay a visit for specifics :)

**Comment by chromy** [comment]
Issues with the [/mission](http://queer-code.org/mission.html) page split to #30. This issue for any github discussion on a future Mission statement.
